import { initializeApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// Fallback config if provisioning failed
const fallbackConfig = {
  apiKey: "mock-api-key",
  authDomain: "mock-project.firebaseapp.com",
  projectId: "mock-project",
  storageBucket: "mock-project.appspot.com",
  messagingSenderId: "123456789",
  appId: "1:123456789:web:abcdef"
};

let firebaseConfig = fallbackConfig;

try {
  // In a real environment, this file would be generated by the tool
  // We'll try to import it dynamically or use the fallback
  // For this applet, we'll assume the user might provide it later
} catch (e) {
  console.warn("Firebase config not found, using fallback. Real database features will not work until configured.");
}

const app = initializeApp(firebaseConfig);
export const auth = getAuth(app);
export const db = getFirestore(app);
export const googleProvider = new GoogleAuthProvider();
